Feat/enemy lifecycle
foxartorg/unity-tower-defence pull request #32
Opened 2022-10-15 16:57 UTC by Peter123456r

I made an enemy counter, a strip and ponies of health, destruction of the enemy. Please check my code. Please check for errors.

2022-10-16 06:28 UTC, Kegori228337 requested changes

2022-10-16 06:28 UTC, Kegori228337 commented on Assets/App/Enemy/Enemy.cs
> +		private void EnemyDamage(int damage) {
Why this EnemyDamage Method is don't used? remove it or make it used.

2022-10-16 06:37 UTC, foxart requested changes

2022-10-16 06:37 UTC, foxart commented on Assets/Scripts/GameScene/CanvasUI.cs
> +			slider.value = health;
what is slider and how it is appeared here?

2022-10-16 06:37 UTC, foxart commented on Assets/App/Enemy/EnemyManager.cs
> +		public Main _main;
why did you change the visibility of this property?

2022-10-16 06:37 UTC, foxart commented on Assets/App/Enemy/EnemyManager.cs
> +		public int counter;
why is this prop public?

2022-10-16 06:37 UTC, foxart commented on Assets/App/Enemy/EnemyManager.cs
> +				this._main.canvasUI.EnemyCounterText(++this.counter);
you shouldn't invoke canvasUI property of this._main, transfer invokation canvasUI -> main and invoke main method from there

2022-10-16 06:37 UTC, foxart commented on Assets/App/Enemy/Enemy.cs
> +			this._enemyManager._main.canvasUI.EnemyCounterText(this._enemyManager.counter);
move invokation of canvasUI method to -> main and invoke proper main method from here

2022-10-16 06:37 UTC, foxart commented on Assets/Scenes/GameScene.unity
> +  enemyCounterText: {fileID: 1707329618}
align the position of text

2022-10-16 06:37 UTC, foxart commented on Assets/App/Enemy/Enemy.cs
> +		private void EnemyDamage(int damage) {
method should be named as ActionEntity and you have EntityAction, pls correct

2022-10-16 06:37 UTC, foxart commented on Assets/App/Enemy/Enemy.cs
> +		private void Update() {
it is expensive method, it will constantly run on each frame, please google about navMeshAgent events on reaching destination or use OnTriggerEnter() to check enemy is reached its destination

2022-10-16 06:37 UTC, foxart commented on Assets/App/Enemy/Enemy.cs
> +		private Slider _enemyHealthSlider;
where did you get this component?

2022-10-16 16:29 UTC, Peter123456r commented
Understood, I will correct.

2022-10-17 13:30 UTC, foxart commented
> Understood, I will correct.

when should we get these updates?

2022-10-21 09:51 UTC, foxart approved these changes

2022-10-21 09:52 UTC, foxart commented
my changes is golden

2022-10-21 09:52 UTC, merged